server {
    listen 8080 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /LiveApp/ {
        proxy_pass https://live.freecam.ro:5443;
        proxy_set_header Host "live.freecam.ro:5443";
        proxy_set_header Referer "https://www.freecam.ro/";
        proxy_set_header Origin "https://www.freecam.ro";
        proxy_ssl_verify off;
        proxy_hide_header Access-Control-Allow-Origin;
        add_header Access-Control-Allow-Origin * always;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
